language: php
php:
#  - 5.4
  #- 5.5
  - hhvm
env:
  - TEST_SUITE=unit
#  - TEST_SUITE=integration TEST_SUITE_INT=int_00
#  - TEST_SUITE=integration TEST_SUITE_INT=int_01
#  - TEST_SUITE=integration TEST_SUITE_INT=int_02
#  - TEST_SUITE=integration TEST_SUITE_INT=int_03
#  - TEST_SUITE=integration TEST_SUITE_INT=int_04
#  - TEST_SUITE=integration TEST_SUITE_INT=int_05
#  - TEST_SUITE=integration TEST_SUITE_INT=int_06
#  - TEST_SUITE=integration TEST_SUITE_INT=int_07
#  - TEST_SUITE=integration TEST_SUITE_INT=int_08
#  - TEST_SUITE=integration TEST_SUITE_INT=int_09
#  - TEST_SUITE=integration TEST_SUITE_INT=int_10
#  - TEST_SUITE=integration TEST_SUITE_INT=int_11
#  - TEST_SUITE=integration_integrity
#  - TEST_SUITE=static_phpcs
#  - TEST_SUITE=static_annotation
matrix:
  allow_failures:
    - php: hhvm
  exclude:
    - php: 5.5
      env: TEST_SUITE=static_phpcs
    - php: 5.5
      env: TEST_SUITE=static_annotation
    - php: 5.5
      env: TEST_SUITE=integration
    - php: hhvm
      env: TEST_SUITE=static_phpcs
    - php: hhvm
      env: TEST_SUITE=static_annotation
    - php: hhvm
      env: TEST_SUITE=integration_integrity
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq postfix
before_script:
  - if [[ "$TEST_SUITE" != "unit" ]]; then sudo bash $TRAVIS_BUILD_DIR/dev/travis/prepare.sh; fi;
  - mysql -uroot -e "SET @@global.sql_mode = NO_ENGINE_SUBSTITUTION"
  # mock mail
  - sudo service postfix stop
  - smtp-sink -d "%d.%H.%M.%S" localhost:2500 1000 &
  # Create DB for Integration tests
  - bash -c "if [ '$TEST_SUITE' == 'integration' ] || [ '$TEST_SUITE' == 'integration_integrity' ]; then mysql -e 'create database magento_integration_tests;'; mv dev/tests/integration/etc/install-config-mysql.travis.php.dist dev/tests/integration/etc/install-config-mysql.php; fi"
  # Install tools for static tests
  - bash -c "if [ '$TEST_SUITE' == 'static_phpcs' ] || [ '$TEST_SUITE' == 'static_annotation' ]; then composer global require "squizlabs/php_codesniffer=1.5.2"; fi"
  - bash -c "if [ '$TRAVIS_PHP_VERSION' == 'hhvm' ]; then sudo bash $TRAVIS_BUILD_DIR/dev/travis/hhvm.sh; fi;"
  - bash -c "if [ '$TRAVIS_PHP_VERSION' != 'hhvm' ]; then sudo bash $TRAVIS_BUILD_DIR/dev/travis/php.sh; fi;"
  - phpenv rehash;
  - composer install --no-interaction --prefer-source --dev
  - if [ '$TEST_SUITE' != 'unit' ]; then cd setup; composer install --no-interaction --prefer-source --dev; cd ..; fi
script:
  - php --version
  - sudo grep ext_entity_whitelist /etc/hhvm/php.ini
  - sudo grep ext_entity_whitelist /home/travis/.phpenv/versions/hhvm-3.4.0~precise/php.ini
  # Unit tests
  - bash -c "if [ '$TEST_SUITE' == 'unit' ] && [ '$TRAVIS_PHP_VERSION' == 'hhvm' ]; then cat $TRAVIS_BUILD_DIR/dev/travis/hhvm/unit.sh | bash; fi"
  - bash -c "if [ '$TEST_SUITE' == 'unit' ] && [ '$TRAVIS_PHP_VERSION' != 'hhvm' ]; then ./vendor/bin/phpunit -c $TRAVIS_BUILD_DIR/dev/tests/unit/phpunit.xml.dist; fi"
  # Integration tests
  - bash -c "if [ '$TEST_SUITE' == 'integration' ] && [ '$TRAVIS_PHP_VERSION' == 'hhvm' ]; then cat $TRAVIS_BUILD_DIR/dev/travis/hhvm/integration.sh | bash; fi"
  - bash -c "if [ '$TEST_SUITE' == 'integration' ] && [ '$TRAVIS_PHP_VERSION' != 'hhvm' ]; then cd dev/tests/integration/; $TRAVIS_BUILD_DIR/vendor/bin/phpunit -c phpunit.xml.dist; fi"
  # Integration integrity tests
  - bash -c "if [ '$TEST_SUITE' == 'integration_integrity' ]; then cd dev/tests/integration/; $TRAVIS_BUILD_DIR/vendor/bin/phpunit -c phpunit.xml.dist testsuite/Magento/Test/Integrity; fi"
  # Static tests [Code Style]
  - bash -c "if [ '$TEST_SUITE' == 'static_phpcs' ]; then cd dev/tests/static; $TRAVIS_BUILD_DIR/vendor/bin/phpunit -c phpunit.xml.dist --filter 'Magento\\\\Test\\\\Php\\\\LiveCodeTest::testCodeStyle'; fi"
  # Static tests [Code Style]
  - bash -c "if [ '$TEST_SUITE' == 'static_annotation' ]; then cd dev/tests/static; $TRAVIS_BUILD_DIR/vendor/bin/phpunit -c phpunit.xml.dist --filter 'Magento\\\\Test\\\\Php\\\\LiveCodeTest::testAnnotationStandard'; fi"
