language: php
php:
#  - 5.5
#  - 5.6
  - hhvm
#  - hhvm-nightly
env:
  matrix:
#    - TEST_SUITE=unit NEED_DB=false
    - TEST_SUITE=integration NEED_DB=true
#  - TEST_SUITE=integration_integrity NEED_DB=true
#  - TEST_SUITE=static_phpcs NEED_DB=false
#  - TEST_SUITE=static_annotation NEED_DB=false
#  - TEST_SUITE=functional NEED_DB=true
#  - TEST_SUITE-test NEED_DB=false
matrix:
  allow_failures:
    - php: hhvm
    - php: 5.6
    - php: hhvm-nightly
  exclude:
    - php: 5.6
      env: TEST_SUITE=static_phpcs
    - php: 5.6
      env: TEST_SUITE=static_annotation
    - php: 5.5
      env: TEST_SUITE=integration
    - php: hhvm
      env: TEST_SUITE=static_phpcs
    - php: hhvm
      env: TEST_SUITE=static_annotation
    - php: hhvm
      env: TEST_SUITE=integration_integrity
    - php: hhvm-nightly
      env: TEST_SUITE=static_phpcs
    - php: hhvm-nightly
      env: TEST_SUITE=static_annotation
    - php: hhvm-nightly
      env: TEST_SUITE=integration_integrity
    - php: 5.6
      env: TEST_SUITE=static_phpcs
    - php: 5.6
      env: TEST_SUITE=static_annotation
    - php: 5.6
      env: TEST_SUITE=functional
    - php: 5.6
      env: TEST_SUITE=integration_integrity
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq postfix
#  - sudo apt-get install -y -qq mlocate
#  - sudo updatedb
  - composer self-update
before_script:
  - chmod a+x $TRAVIS_BUILD_DIR/dev/travis/parallel
  # Mock mail
  - sudo service postfix stop
  - smtp-sink -d "%d.%H.%M.%S" localhost:2500 1000 &
  # Install MySQL 5.6, create DB for integration tests
  - if [[ "$NEED_DB" == "true" ]]; then bash $TRAVIS_BUILD_DIR/dev/travis/install-mysql-5.6.sh; fi;
  - mysql -uroot -e "SET @@global.sql_mode = NO_ENGINE_SUBSTITUTION"
  # Create DB for Integration tests
  - if [[ "$NEED_DB" == "true" ]]; then mysql -e 'create database magento_integration_tests;'; mv dev/tests/integration/etc/install-config-mysql.travis.php.dist dev/tests/integration/etc/install-config-mysql.php; fi
  - bash -c "if [ '$TEST_SUITE' == 'static_phpcs' ] || [ '$TEST_SUITE' == 'static_annotation' ]; then composer global require "squizlabs/php_codesniffer=1.5.2"; fi"
  - bash -c "if [ '$TRAVIS_PHP_VERSION' == 'hhvm' ]; then sudo bash $TRAVIS_BUILD_DIR/dev/travis/hhvm.sh; fi;"
  - bash -c "if [ '$TRAVIS_PHP_VERSION' != 'hhvm' ]; then sudo bash $TRAVIS_BUILD_DIR/dev/travis/php.sh; fi;"
  - phpenv rehash;
  - composer install --no-interaction --prefer-source --dev >&2> /dev/null; if [[ $? -ne 0 ]]; then exit $?; fi
  - export DISPLAY=:99.0
  - bash -c "if [ '$TEST_SUITE' == 'functional' ]; then cd ./dev/tests/functional/; composer install --no-interaction --prefer-source --dev; cd $TRAVIS_BUILD_DIR; fi"
  - bash -c "if [ '$TEST_SUITE' == 'functional' ]; then sudo bash $TRAVIS_BUILD_DIR/dev/travis/install-nginx.sh; fi"
  - bash -c "if [ '$TEST_SUITE' == 'functional' ]; then sudo bash $TRAVIS_BUILD_DIR/dev/travis/install-magento.sh; fi"
  - bash -c "if [ '$TEST_SUITE' == 'functional' ]; then sudo bash $TRAVIS_BUILD_DIR/dev/travis/start-servers.sh; fi"
  - bash -c "if [ '$TEST_SUITE' == 'functional' ]; then sudo bash $TRAVIS_BUILD_DIR/dev/travis/install-firefox.sh; fi"
script:
  # Unit tests
  - bash -c "if [ '$TEST_SUITE' == 'unit' ] && [ '$TRAVIS_PHP_VERSION' == 'hhvm' ]; then cd ./dev/tests/unit/; ls -dX ./testsuite/Magento/* | grep -v _files | $TRAVIS_BUILD_DIR/dev/travis/parallel --nn --gnu -P 5 'echo \"Running {} tests\"; hhvm -c ${TRAVIS_BUILD_DIR}/dev/travis/php.ini -v Eval.Jit=1 -f ${TRAVIS_BUILD_DIR}/vendor/phpunit/phpunit/phpunit -- --configuration ./phpunit.xml.dist {};' || exit 1; fi"
  - bash -c "if [ '$TEST_SUITE' == 'unit' ] && [ '$TRAVIS_PHP_VERSION' != 'hhvm' ]; then cd ./dev/tests/unit/; ls -dX ./testsuite/Magento/* | grep -v _files | $TRAVIS_BUILD_DIR/dev/travis/parallel --nn --gnu -P 5 'echo \"Running {} tests\"; php -f ${TRAVIS_BUILD_DIR}/vendor/phpunit/phpunit/phpunit -- --configuration ./phpunit.xml.dist {};' || exit 1; fi"
  # Integration tests
  - bash -c "if [ '$TEST_SUITE' == 'integration' ] && [ '$TRAVIS_PHP_VERSION' == 'hhvm' ]; then bash $TRAVIS_BUILD_DIR/dev/travis/hhvm/integration.sh 'hhvm -c $TRAVIS_BUILD_DIR/dev/travis/php.ini $TRAVIS_BUILD_DIR/vendor/phpunit/phpunit/phpunit -- ' $TRAVIS_BUILD_DIR; fi"
  - bash -c "if [ '$TEST_SUITE' == 'integration' ] && [ '$TRAVIS_PHP_VERSION' != 'hhvm' ]; then  $TRAVIS_BUILD_DIR/dev/travis/hhvm/integration.sh '$TRAVIS_BUILD_DIR/vendor/bin/phpunit'; fi"
  # Integration integrity tests
  - bash -c "if [ '$TEST_SUITE' == 'integration_integrity' ]; then cd dev/tests/integration/; $TRAVIS_BUILD_DIR/vendor/bin/phpunit -c phpunit.xml.dist testsuite/Magento/Test/Integrity; fi"
  # Static tests [Code Style]
  - sh -c "if [ '$TEST_SUITE' = 'static_phpcs' ]; then cd dev/tests/static; ./../../../vendor/bin/phpunit -c phpunit.xml.dist --filter 'Magento\\\\Test\\\\Php\\\\LiveCodeTest::testCodeStyle'; fi"
  # Static tests [Code Style]
  - sh -c "if [ '$TEST_SUITE' = 'static_annotation' ]; then cd dev/tests/static; ./../../../vendor/bin/phpunit -c phpunit.xml.dist --filter 'Magento\\\\Test\\\\Php\\\\LiveCodeTest::testAnnotationStandard'; fi"
